<a href="https://colab.research.google.com/github/Junaidma002/Introduction-to-python/blob/main/python_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Creating data frame from dictionary
import pandas
teamgoals={
    "teams":["Spain","portugal"],
    "goals":[1,2]   
}
teamgoaldf=pandas.DataFrame(teamgoals)
print(teamgoaldf)

      teams  goals
0     Spain      1
1  portugal      2


In [5]:
from google.colab import files
supermarket=files.upload()

Saving Supermarket_sales.csv to Supermarket_sales.csv


In [6]:
import pandas
dataframe=pandas.read_csv("Supermarket_sales.csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [9]:
print(dataframe.head(10))

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
5   6  699-14-3026      C  Naypyitaw       Normal    Male   
6   7  355-53-5943      A     Yangon       Member  Female   
7   8  315-22-5665      C  Naypyitaw       Normal  Female   
8   9  665-32-9167      A     Yangon       Member  Female   
9  10  692-92-5582      B   Mandalay       Member  Female   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       

In [11]:
print(dataframe.tail(8))

       No    InvoiceID Branch       City Customertype  Gender  \
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
994  Electronic accessories      60.95         1   3.0475    63.9975   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6

In [12]:
dataframe.loc[1]

No                                              2
InvoiceID                             226-31-3081
Branch                                          C
City                                    Naypyitaw
Customertype                               Normal
Gender                                     Female
Productline                Electronic accessories
Unitprice                                   15.28
Quantity                                        5
Tax                                          3.82
Total                                       80.22
Date                                     3/8/2019
Time                                        10:29
Payment                                      Cash
cogs                                         76.4
gross_margin_percentage                  4.761905
gross_iincome                                3.82
Rating                                        9.6
Name: 1, dtype: object

In [13]:
dataframe.loc[4]

No                                         5
InvoiceID                        373-73-7910
Branch                                     A
City                                  Yangon
Customertype                          Normal
Gender                                  Male
Productline                Sports and travel
Unitprice                              86.31
Quantity                                   7
Tax                                  30.2085
Total                               634.3785
Date                                2/8/2019
Time                                   10:37
Payment                              Ewallet
cogs                                  604.17
gross_margin_percentage             4.761905
gross_iincome                        30.2085
Rating                                   5.3
Name: 4, dtype: object

In [14]:
dataframe["City"]

0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
         ...    
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 1000, dtype: object

In [15]:
dataframe[["City","Branch"]]

City Branch
0       Yangon      A
1    Naypyitaw      C
2       Yangon      A
3       Yangon      A
4       Yangon      A
..         ...    ...
995  Naypyitaw      C
996   Mandalay      B
997     Yangon      A
998     Yangon      A
999     Yangon      A

[1000 rows x 2 columns]

In [29]:
#droping specific column
dataframe=dataframe.drop(["Quantity"],axis=1)
dataframe.head(4)


No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice     Total       Date   Time      Payment  \
0       Health and beauty      74.69  548.9715   1/5/2019  13:08      Ewallet   
1  Electronic accessories      15.28   80.2200   3/8/2019  10:29         Cash   
2      Home and lifestyle      46.33  340.5255   3/3/2019  13:23  Credit card   
3       Health and beauty      58.22  489.0480  1/27/2019  20:33      Ewallet   

     cogs  gross_iincome  
0  522.83        26.1415  
1   76.40         3.8200  
2  324.31        16.2155  
3  465.76        23.2880

In [28]:
#droping specific row
dataframe=dataframe.drop([5],axis=0)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_iincome  
0      Ewallet  522.83        26.1415  
1         Cash   76.40         3.8200  
2  Credit card  324.31        16.2155  
3      Ewallet  465.76        23.2880

In [31]:
max_overrall=dataframe.Unitprice.idxmax()
print(max_overrall)

122


In [32]:
max_overrall=dataframe.Unitprice.max()
print(max_overrall)

99.96


In [33]:
print(dataframe.loc[122])

No                             123
InvoiceID              219-22-9386
Branch                           B
City                      Mandalay
Customertype                Member
Gender                        Male
Productline      Sports and travel
Unitprice                    99.96
Total                      944.622
Date                      3/9/2019
Time                         17:26
Payment                Credit card
cogs                        899.64
gross_iincome               44.982
Name: 122, dtype: object


In [38]:
min_overrall=dataframe.Unitprice.min()
print(min_overrall)

10.08


In [39]:
min_overrall=dataframe.Unitprice.idxmin()
print(min_overrall)

944


In [40]:
print(dataframe.loc[944])

No                             945
InvoiceID              333-23-2632
Branch                           A
City                        Yangon
Customertype                Member
Gender                        Male
Productline      Health and beauty
Unitprice                    10.08
Total                       74.088
Date                     3/28/2019
Time                         20:14
Payment                       Cash
cogs                         70.56
gross_iincome                3.528
Name: 944, dtype: object


In [41]:
dataframe.loc[dataframe["Customertype"]=="Normal"]

No    InvoiceID Branch       City Customertype  Gender  \
1      2  226-31-3081      C  Naypyitaw       Normal  Female   
2      3  631-41-3108      A     Yangon       Normal    Male   
4      5  373-73-7910      A     Yangon       Normal    Male   
7      8  315-22-5665      C  Naypyitaw       Normal  Female   
12    13  365-64-0515      A     Yangon       Normal  Female   
..   ...          ...    ...        ...          ...     ...   
992  993  745-74-0715      A     Yangon       Normal    Male   
993  994  690-01-6631      B   Mandalay       Normal    Male   
995  996  233-67-5758      C  Naypyitaw       Normal    Male   
996  997  303-96-2227      B   Mandalay       Normal  Female   
998  999  347-56-2442      A     Yangon       Normal    Male   

                Productline  Unitprice      Total       Date   Time  \
1    Electronic accessories      15.28    80.2200   3/8/2019  10:29   
2        Home and lifestyle      46.33   340.5255   3/3/2019  13:23   
4         Sports and travel      86.31   634.3785   2/8/2019  10:37   
7        Home and lifestyle      73.56   772.3800  2/24/2019  11:38   
12   Electronic accessories      46.95   246.4875  2/12/2019  10:25   
..                      ...        ...        ...        ...    ...   
992  Electronic accessories      58.03   121.8630  3/10/2019  20:46   
993     Fashion accessories      17.49   183.6450  2/22/2019  18:35   
995       Health and beauty      40.35    42.3675  1/29/2019  13:46   
996      Home and lifestyle      97.38  1022.4900   3/2/2019  17:16   
998      Home and lifestyle      65.82    69.1110  2/22/2019  15:33   

         Payment    cogs  gross_iincome  
1           Cash   76.40         3.8200  
2    Credit card  324.31        16.2155  
4        Ewallet  604.17        30.2085  
7        Ewallet  735.60        36.7800  
12       Ewallet  234.75        11.7375  
..           ...     ...            ...  
992      Ewallet  116.06         5.8030  
993      Ewallet  174.90         8.7450  
995      Ewallet   40.35         2.0175  
996      Ewallet  973.80        48.6900  
998         Cash   65.82         3.2910  

[498 rows x 14 columns]

In [42]:
dataframe.loc[dataframe["Gender"]=="Male"]

No    InvoiceID Branch       City Customertype Gender  \
2      3  631-41-3108      A     Yangon       Normal   Male   
3      4  123-19-1176      A     Yangon       Member   Male   
4      5  373-73-7910      A     Yangon       Normal   Male   
11    12  529-56-3974      B   Mandalay       Member   Male   
13    14  252-56-2699      A     Yangon       Normal   Male   
..   ...          ...    ...        ...          ...    ...   
992  993  745-74-0715      A     Yangon       Normal   Male   
993  994  690-01-6631      B   Mandalay       Normal   Male   
995  996  233-67-5758      C  Naypyitaw       Normal   Male   
997  998  727-02-1313      A     Yangon       Member   Male   
998  999  347-56-2442      A     Yangon       Normal   Male   

                Productline  Unitprice     Total       Date   Time  \
2        Home and lifestyle      46.33  340.5255   3/3/2019  13:23   
3         Health and beauty      58.22  489.0480  1/27/2019  20:33   
4         Sports and travel      86.31  634.3785   2/8/2019  10:37   
11   Electronic accessories      25.51  107.1420   3/9/2019  17:03   
13       Food and beverages      43.19  453.4950   2/7/2019  16:48   
..                      ...        ...       ...        ...    ...   
992  Electronic accessories      58.03  121.8630  3/10/2019  20:46   
993     Fashion accessories      17.49  183.6450  2/22/2019  18:35   
995       Health and beauty      40.35   42.3675  1/29/2019  13:46   
997      Food and beverages      31.84   33.4320   2/9/2019  13:22   
998      Home and lifestyle      65.82   69.1110  2/22/2019  15:33   

         Payment    cogs  gross_iincome  
2    Credit card  324.31        16.2155  
3        Ewallet  465.76        23.2880  
4        Ewallet  604.17        30.2085  
11          Cash  102.04         5.1020  
13       Ewallet  431.90        21.5950  
..           ...     ...            ...  
992      Ewallet  116.06         5.8030  
993      Ewallet  174.90         8.7450  
995      Ewallet   40.35         2.0175  
997         Cash   31.84         1.5920  
998         Cash   65.82         3.2910  

[498 rows x 14 columns]

In [47]:
import numpy as np
student_marks_BA=[12,14,10]
marksarray=np.array(student_marks_BA)
print(marksarray)

[12 14 10]


In [48]:
import numpy as np
student_marks=[[12,14,10],[15,19,20],[11,15,19]]
marksarray=np.array(student_marks)
print(marksarray)

[[12 14 10]
 [15 19 20]
 [11 15 19]]


In [49]:
import numpy as np
student_marks=[[12,14],[15,19],[11,15],[13,17]]
marksarray=np.array(student_marks)
print(marksarray)

[[12 14]
 [15 19]
 [11 15]
 [13 17]]


In [50]:
value1=np.arange(20)
print(value1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
values2=np.arange(5,11)
print(values2)

[ 5  6  7  8  9 10]


In [55]:
#creating zero array
zeroarray=np.zeros(5)
print(zeroarray)

[0. 0. 0. 0. 0.]


In [57]:
zeroarray=np.zeros((2,6))
print(zeroarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [60]:
zeroarray2=np.zeros((4,2))
print(zeroarray2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [61]:
onesarray=np.ones(5)
print(onesarray)

[1. 1. 1. 1. 1.]


In [63]:
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [64]:
identityarray=np.eye(10)
print(identityarray)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [65]:
#length of array
len(zeroarray)

4

In [66]:
#reshaping an array
firstarray=np.array([[10,20,30,40],[2,4,6,8],[5,10,15,20]])
print(firstarray.shape)

(3, 4)


In [68]:
secondarray=firstarray.reshape(4,3)
print(secondarray)

[[10 20 30]
 [40  2  4]
 [ 6  8  5]
 [10 15 20]]


In [70]:
thirdarray=firstarray.reshape(6,2)
print(thirdarray)

[[10 20]
 [30 40]
 [ 2  4]
 [ 6  8]
 [ 5 10]
 [15 20]]


In [73]:
#with random numbers
values=np.random.randint(1,3,5)
print(values)

[2 2 1 2 1]


In [75]:
values=np.random.randint(44,88,6)
print(values)

[51 70 74 65 55 55]


In [78]:
values=np.random.randint(25,50,(4,3))
print(values)

[[30 36 40]
 [31 31 26]
 [49 48 36]
 [34 27 27]]
